FROM node:10 as build-stage
# make a directory if not exist where my app is copied in container
WORKDIR /app
# copy package.json inside container working directory (NOTE WHEN YOU ISSUE WORKDIR COMMAND, IT WILL BECOME CURRENT DIRECTORY FOR FUTURE PATH
COPY package*.json /app/
# run npm install inside working directory
RUN npm install
# copy rest of project content inside working directory
# NOTE HAMESHA PEHLA ARGUMENT IS FOR HOST MACHINE IN DOCKER
COPY ./ /app/

# provide the continer port
EXPOSE 3000
# below command will run when container starts
CMD [ "npm","run","start" ]
